<?php

return [
    'PUBLIC_API_BASE' => 'https://bookapp.test/pgw',
    'AUTHORIZE_LOGIN_ID' => '3Ca5hYQ6h',
    'AUTHORIZE_TRANSACTION_KEY' => '8bt8Kr5gPZ3ZE23C',
    'AUTHORIZE_ENV' => 'sandbox',
    'STRIPE_SECRET_KEY' => 'ssssssssssssssssssssssssssssssssssssssssssssss',
    'MIDTRANS_SERVER_KEY' => 'Midtrans',
    'MIDTRANS_BASE' => 'https://app.sandbox.midtrans.com/snap/v1/transactions',
    'MOLLIE_API_KEY' => 'Mollie',
    'MYFATOORAH_API_KEY' => 'My-Fatoorah',
    'MYFATOORAH_BASE' => 'https://apitest.myfatoorah.com',
    'XENDIT_SECRET_KEY' => 'Xendit',
    'XENDIT_BASE' => 'https://api.xendit.co',
    'FLW_SECRET_KEY' => 'Flutterwave',
    'FLW_BASE' => 'https://api.flutterwave.com',
    'PAYPAL_CLIENT_ID' => 'pppppppp',
    'PAYPAL_SECRET' => 'ppppppppppppfsdfsdf',
    'PAYPAL_BASE' => 'https://api-m.sandbox.paypal.com',
    'PHONEPE_BASE' => 'https://api-preprod.phonepe.com/apis/pg-sandbox',
    'PHONEPE_MERCHANT_ID' => 'TEST-M2246YU2T4XSL_25051',
    'PHONEPE_SALT_KEY' => 'ZjczZTA1OWMtZjkxYS00ZjJhLTgxMjItNDdkZTNlNmUyYzhi',
    'PHONEPE_SALT_INDEX' => '1',
    'MP_ACCESS_TOKEN' => 'MercadoPago',
    'MP_BASE' => 'https://api.mercadopago.com',
    'PAYSTACK_SECRET_KEY' => 'sk_test_4ac9f2c43514e3cc08ab68f922201549ebda1bfd',
    'PAYSTACK_BASE' => 'https://api.paystack.co',
    'TOYYIBPAY_BASE' => 'https://dev.toyyibpay.com',
    'TOYYIBPAY_SECRET_KEY' => 'dfdasfdsfasdf',
    'TOYYIBPAY_CATEGORY_CODE' => 'tttt',
    'MONNIFY_BASE' => 'https://sandbox.monnify.com',
    'MONNIFY_API_KEY' => 'MK_TEST_8755DDQ66C',
    'MONNIFY_SECRET_KEY' => '5APXHLXN5K4H0TLCA9TA1T9CPQEBAFE3',
    'MONNIFY_CONTRACT_CODE' => '9442496187',
    'NOWPAYMENTS_API_KEY' => '9N7MHQ6-RF4MSWT-GPMW616-QSKT2V9',
    'NOWPAYMENTS_BASE' => 'https://api.nowpayments.io/v1',
];
